[project]
name = "timeseries-pipelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kedro>=1.0.0",
    "sktime>=0.40.1",
]
